### PR TITLE
Use getBlockPrefix instaad of override deprecated getName

### PR DESCRIPTION
**Pull request by Koc**

### CODE REVIEW

**Comment by Koc** [comment]
@Haehnchen see https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md ("If you want to customize the block prefix of a type ...")

**Comment by hoshsadiq** [comment]
Shouldn't this be based on the Symfony version?

**Comment by Koc** [comment]
@hoshsadiq this template also uses `configureOptions` method introduced in later versions (~2.7 or maybe ~2.8).

**Comment by hoshsadiq** [comment]
Oh sorry, this is the template for 2.8 anyway. Didn't realise!

**Pull request merged**
