### PR TITLE
[WIP] Completion for YAML tags, keywords and PHP constants

### PR DESCRIPTION
**Pull request by King2500**
* Adds completion for generic YAML tags like `!php/const`, `!!str` etc
* Adds completion for specific YAML tags in services.yaml like `!tagged` etc
* Adds completion and goto definition for PHP constants (class and global) after `!php/const <caret>`
* Adds completion for YAML keywords like `true`, `false`, `null` etc

*Todo: describe more details*

**It's still work in progress:**
I have to add some tests

**Screenshots:**

image

image

### CODE REVIEW

**Comment by Haehnchen** [comment]
can i support here somehow? there some commit in the code. also about `2019.2`.
currently there no blocker to higher the `since` build, this allows to use java11

**Comment by King2500** [comment]
It needs some testcases where completion should come up and where not.

**Comment by King2500** [comment]
@Haehnchen Do you know why tests fail with jdk8 ?
`Expected feature release number in range of 9 to 14, but got: 8`

Is Travis configured correctly?

**Comment by King2500** [comment]
Notes to myself:
Todos:
- allow YAML tags (PHP constants) inside YAML keys (see https://github.com/symfony/symfony/issues/22854)
- Filter PHP constants completion (remove non-public class constants)

**Comment by Haehnchen** [comment]
moved in all via: https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1364

**Comment by King2500** [comment]
:+1:

should i just close this?

**Comment by Haehnchen** [comment]
yes closing this ;)

**Pull request closed without merging**
