### PR TITLE
[VIP] TravisCi Integration

### PR DESCRIPTION
**Pull request by Sorien**

### CODE REVIEW

**Comment by Sorien** [comment]
@Haehnchen pls setup Travis for this repository

**Comment by Haehnchen** [comment]
ok nice so far, missing plugins:

* twig
* yaml
* php-annotations (https://plugins.jetbrains.com/update/index?pr=&updateId=18927)

 can you add them?

**Comment by Sorien** [comment]
@Haehnchen there are some compilation errors can you try look at it?

**Comment by Sorien** [comment]
1 Error, 4 Failed other tests running fine ... that's all I can do 

There is one file with wrong name /assets/Twig**n**amedAssetsServiceParser.java should be named /assets/Twig**N**amedAssetsServiceParser.java (i couldnt rename it directly on win commit dc843b2 and cf49266)

**Comment by Haehnchen** [comment]
thx, its working. :thumbsup: removed the memory leak in a crazy commit :)
https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/34c75533f646aa7037f3e571482dba2482073cd1

Can you combine the commits into one? its then ready to merge

**Comment by Sorien** [comment]
i had to rename TwigTranslationFixturesTest.java to TwigTranslationFixturesTestCase.java couse ant junit is not ignoring abstract classes

**Comment by Haehnchen** [comment]
:thumbsup:

**Pull request merged**
