### PR TITLE
Migrate Project structure to use gradle

### PR DESCRIPTION
**Pull request by cedricziel**
The project depends on the toolbox and the annotation plugin, so this
will only ever build if they update first.

### CODE REVIEW

**Comment by cedricziel** [comment]
Two test classes were not found by the ant script glob. I renamed them in 68b83a5 to get into a state where we have been before and the build should become stable again for the 2017.3 line.

**Comment by Haehnchen** [comment]
@cedricziel tests about PHPSTORM_ENV can be disabled. simply they are not working without a full project right now.

**Comment by cedricziel** [comment]
@Haehnchen Alright, the PRs are all ready to be merged.

We should start with https://github.com/Haehnchen/idea-php-toolbox/pull/79 and tag it with 0.4.7 or something else i can then adjust in the other PRs to.

Then https://github.com/Haehnchen/idea-php-annotation-plugin/pull/110 needs another run on travis, but i expect it to be green as well.

After that, the main plugin (this PR) is next. The laravel plugin one is green as well.

Thx in advance!

**Comment by cedricziel** [comment]
@Haehnchen Upgraded to stable 2018.1 platform requirements, fixed 2 OpenAPI issues and it's green now.

**Pull request merged**
