### PR TITLE
Make compatible with new Deployment API

### PR DESCRIPTION
**Pull request by Leneshka-jb**
PhpStorm 2016.3.1 EAP opens tomorrow, and it brings changes in Deployment plugin API. Unfortunately they break Symfony plugin. Here are compatibility changes, please apply them and publish new plugin build in repository.

### CODE REVIEW

**Comment by hoshsadiq** [comment]
Tests failing. Wouldn't this merge make it incompatible with older versions of IntelliJ? I feel like this can be handled more gracefully rather than just say it we won't support older versions of IntelliJ

**Comment by Leneshka-jb** [comment]
Unfortunatelly Deployment API changed incompatibly, so you will have to
make separate build for 2013.3 and earlier.

Best regards,

Elena Shaverdova
Software developer

JetBrains GmbH
Elsenheimerstr. 47
80687 München
Tel: +49 (0) 89 255 596 583
Fax: +49 (0) 89 255 596
588elena.shaverdova@jetbrains.comhttp://www.jetbrains.com
Handelsregister: Amtsgericht München, HRB 187151
Geschäftsführer: Sergey Dmitriev, Maksim Mosienko

**Comment by Haehnchen** [comment]
currently there is no public enviroment available: IntelliJ IDEA `163.9166` vs PhpStorm `163.9735`. So i need to wait for next IDEA 2016.3 EAP release before shipping this

**Comment by Haehnchen** [comment]
@Leneshka-jb thx. i resolved the conflicts becasue of new build environments and merged into master

**Pull request closed without merging**
