### PR TITLE
Change static libraryRoots to dynamic LibraryRootProvider implementations

### PR DESCRIPTION
**Pull request by King2500**
This allows to load meta files only when Symfony plugin is enabled in project settings:
image

Non-Symfony projects don't get bloated with unneeded memory consumption when PhpStorm indexes php files.

### CODE REVIEW

**Comment by Haehnchen** [comment]
@King2500 can you check the failing tests?

**Comment by King2500** [comment]
@Haehnchen I don't understand why that specific test fails: `testCaseInsensitiveParameter`

I tried running that particular test locally and it passes.

**Comment by King2500** [comment]
@Haehnchen I narrowed down the problem.

It looks like the `PhpLibraryRootProvider` EP is not working properly in PhpStorm 2018.x releases.

I suggest going to next major release of Symfony plugin: version 0.18.x which requires PhpStorm 2019.1+

This meta feature is not working for older releases anyway.

**Comment by King2500** [comment]
For 2019.1+ releases: `<idea-version since-build="191.0"/>`

**Comment by King2500** [comment]
=> #1300

**Comment by King2500** [comment]
@Haehnchen Is there anything I can do before this can be merged?

**Comment by Haehnchen** [comment]
@King2500 can you please rebase against master? we can also increase the since build, to drop older version now.

**Comment by King2500** [comment]
@Haehnchen did so.

Wondering why this fails. I'll check if it fails in local/IDE (Windows) tests as well.

**Comment by King2500** [comment]
This particular test runs fine on my local Windows dev machine:
image

**Comment by King2500** [comment]
Here is some context, but i still don't understand the actual problem :(
https://github.com/JetBrains/intellij-community/blob/248073d309e3d1694196863c1e75267f76f25c25/platform/projectModel-impl/src/com/intellij/openapi/roots/impl/ProjectRootManagerImpl.java#L346

**Comment by Haehnchen** [comment]
thx merged via https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1545

**Pull request closed without merging**
