### PR TITLE
add PhpStorm 2017.3 environment

### PR DESCRIPTION
**Pull request by Haehnchen**

### CODE REVIEW

**Comment by cedricziel** [comment]
Hi Daniel, have you considered moving to Gradle?

**Comment by Haehnchen** [comment]
@cedricziel yes its on my todo. i just want to migrate our travis build enviroment :)

**Comment by cedricziel** [comment]
2017.3 is currently failing for me as well - https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FWI-39152

I hope they fix it with 2017.3.2 ;)

**Comment by Haehnchen** [comment]
@cedricziel now some other errors on `2017.3.2` build :)

**Pull request merged**
